#  dom.urea.stack.mac
#
variable integer,dimen
variable real,height
variable real,sigma
variable real,delta
#
sigma =  0.006
dimen =  1
#
read
  free 8.218, 8.218, 23.713, 90.,90.,120.
#
do i[0]=0,dimen-1
  do i[1]=0,dimen-1
    @dom.urea.stack.make i[0],i[1],  80
  enddo
enddo
#
@dom.urea.stack.trans
#
save
  outfile dom.urea.stack.list
  omit ncell
  run
exit
#
read
  free 8.218, 8.218, 11.017, 90.,90.,120.
#
@dom.urea.stack.replace
@dom.urea.stack.fourier stack
