# makelayers.mac
#
variable integer,width
width = int(4.5 * p_ab/r[201])
#
read
cell STRU/$1.cell,width,width,2
#
boundary hkl, 0, 0, 1,  0.5,inside
boundary hkl, 0, 0,-1,  1.3,inside
purge
#
save
  outf STRU/$1.layer
  write all
  run
exit
#
#@plot_xbs w1.xbs
#
symm
  angle 180.0
  type  proper
  mode  repl
  sel   all
  incl  all
  orig  0.333333, 0.666667, 0.00
  uvw   0,0,1
  trans 0.00, 0.00, 0.00
  run
exit
#
save
  outf STRU/$1.rotated
  run
exit
#@plot_xbs w2.xbs
