# Macro to run all exercise macros
# This just checks if they run - not if the result is sensible (for now)

set wait,off

# Exercises - CHAPTER 3
cd Chapter_03
@ex_01
@ex_02
@ex_03
@ex_04
@ex_05
@ex_06
@ex_07
@cleanup
cd ..

# Exercises - CHAPTER 4
cd Chapter_04
@ex_01
@ex_02
@ex_03 lmo
@ex_03 ni
@cleanup
cd ..

# Exercises - CHAPTER 5
cd Chapter_05
@ex_01 0.5,-0.5,0.5,-0.5,0.25
@ex_02 0.5,-0.5,0.5,-0.5,0.25
@ex_03
@ex_04
@cleanup
cd ..

# Exercises - CHAPTER 6
cd Chapter_06
@ex_01
@ex_02
@ex_03
@ex_04 20
@ex_05 20
@cleanup
cd ..

# Exercises - CHAPTER 7
cd Chapter_07
@ex_01 0.25
@ex_02 0.25
@ex_03 0.25, hex
@ex_03 0.25, cub
@ex_04
@cleanup
cd ..

# Exercises - CHAPTER 8
cd Chapter_08
@ex_01
@ex_02
@ex_03
@cleanup
cd ..

# Exercises - CHAPTER 9
cd Chapter_09
@ex_01 25, neutron
@ex_02 20, neutron, 1.5, 0.1, linear
@ex_03 7, 7, 30
@ex_04 7, 7, 30
@ex_05 6, 6, 4, 40
@cleanup
cd ..

# Exercises - CHAPTER 10
cd Chapter_10
@ex_01
@ex_02
@ex_03
@ex_04
@ex_05
@cleanup
cd ..


