kuplot
############################################################
# Plot simulation results of Exercise  4.1 :
############################################################
#
rese
buff 0.03,0.00,0.08,0.08
load cr,ex_03_xy.plot
#
msiz 1,0.05
#
skal -60,50,-25,25
mark 20,10
fset 2
aver 50.0/110.0
tit1
tit2
achx
achy
fnam off
grid on
font just,cent
tit1 Exercise 3
tit2 xy plane
#
plot
#
exit              # back to suite level
