plot
  prog kuplot
  ext all
  select all
  set 0,8,6,0.8
  set 1,3,6,1.0
#
  vec  0, 0, 0
  uvw  0, 0, 1
  abs  1, 0, 0
  ord  0, 1, 0
  thick 1.0
  outfile sro_001.plot
  run
#
  vec  0, 0, 0
  uvw  1, 0, 1
  abs -1, 0, 1
  ord  0,-1, 0
  thick 1.0
  outfile sro_101.plot
  run
#
  prog atoms
  ext x,-5.0,5.0
  ext y,-5.0,5.0
  ext z,-5.0,5.0
  vec  0, 0, 0
  uvw  0, 0, 1
  abs  1, 0, 0
  ord  0, 1, 0
  thick 9999.0
  outfile sro.inp
  run
exit
