#
# ex_04.plot.three.mac
#
############################################################
#
#  Writes the sorted 4H structure to be plotted with KUPLOT
#
############################################################
#
plot
  prog   kuplot
  outf   "$1.%2D.plot",$2
  uvw    1,0,0
  abs    0,0,1
  ord    1,2,0
  ext    all
  ext    x,-100,100
  ext    y,-100,100
  vect   0.0,0.0,0.0
  thick  1000.
  sel    all
  set    1, 3, 1, 1.0
  set    2, 3, 3, 1.0
  set    3, 3, 6, 1.0
  run
exit
