#
#  ex_04.fourier.mac
#
############################################################
#
#  Calculates teh Fourier transform along the 10L rod 
#
############################################################
#
four
  ll   $1 ,   $2, -0.5
  lr   $1 ,   $2,  2.5
  ul   $1 ,   $2, -0.5
  na   151
  no     1
  abs    l
  ord    h
  lots   box,1,1,50,20,yes
  set  aver,0.0
  run
exit
output
  outfile "sorted.%1D%1Dl_%2D.inte",$1,$2,$3
  value inte
  run
exit
