read
cell "STRU/$1.%4D.cell",kid
@stapel $1,radius_sub, stack_shell
@shift radius_sub
find env,Zn, 0.0,0.0,0.0, 0.0, 0.9*lat[1]
if(env[1].gt.0) then
  @center x[env[1]],y[env[1]],z[env[1]]
endif
#
@trans2cart
#
boundary sphere,radius_sub
#
purge
save
  outf "STRU/$1.%4D.%4D.%4D.sub",kid,indiv,i[12]
  omit ncell
  omit  gene
  omit  scat
  omit  adp
  run
exit
#
if(n[1].gt.1) then
@plot.cif.shell single_sub,i[12]
endif
