kuplot
############################################################
# Plot simulation results of Exercise  4.2 :
############################################################
#
rese
load cr,ex_02.plot
skal -6,80,-40,40
aver 1
achx x (\A)
achy y (\A)
mark 6,10
fnam off
fset 2
grid on
font just,cent
tit2 Sinusoidal row of atoms
plot
#
############################################################
exit
