#
#
############################################################
#
#
rese
load xy, "DATA/single.%4D.%4D.%6.1F.tth",nint($1), nint(abs($2)), $3
#
skal xmin[1],xmax[1],0.0 ,ymax[1]*1.02
mark
achx r [\A]
achy Intensity
tit1 Carbon nanotube
tit2 X-ray powder pattern
fnam off
plot
wait return
rese
load xy, "DATA/single.%4D.%4D.%6.1F.gr",nint($1), nint(abs($2)), $3
#
skal xmin[1],xmax[1],ymin[1]*1.02,ymax[1]*1.02
mark
achx r [\A]
achy G(r)
tit1 Carbon nanotube
tit2 X-ray PDF
fnam off
plot
