# creates a Wurtzite double layer
#
variable real,width
width = 5
#
read
cell $1.cell,width,width,2
#
boundary hkl, 0, 0, 1,  0.5,inside
boundary hkl, 0, 0,-1,  1.3,inside
purge
#
save
  outf $1.layer
  write all
  run
exit
#
symm
  angle 180.0
  type  proper
  mode  repl
  sel   all
  incl  all
  orig  0.333333, 0.666667, 0.00
  uvw   0,0,1
  trans 0.00, 0.00, 0.00
  run
exit
#
save
  outf $1.rotated
  run
exit
