@ran 50,0.3
#
mmc
  set neig,rese
#
  set vec,1,1,1, 1, 0, 0
  set vec,2,1,1, 0, 1, 0
  set vec,3,1,1,-1, 0, 0
  set vec,4,1,1, 0,-1, 0
  set neig,vec,1,2,3,4
  set neig,add
#
  set vec,5,1,1, 1, 1, 0
  set vec,6,1,1,-1, 1, 0
  set vec,7,1,1, 1,-1, 0
  set vec,8,1,1,-1,-1, 0
  set neig,vec,5,6,7,8
#
  set mode, 1.0, swchem,all
  set targ,1,corr,cu,void,$1,0.0,CORR
  set targ,2,corr,cu,void,$2,0.0,CORR
  set cyc, 100*n[1]
  set feed,  5*n[1]
  set temp,$3
  run
exit
#
save example.stru
