############################################################
# EXERCISE NANOPARTICLES  1
#
#    Simulate a simple spherical nanoparticle, calculate the
#    PDF and the powder pattern.
#
############################################################
#
if($0.ne.2) then
  echo
  echo "Usage:"
  echo " @ex_01.mac <diameter>, { xray | neutron }"
  echo
  wait return
  continue discus
endif
#
############################################################
# First we read just a single unit cell, in order to know
# the lattice constants. This allows us to determine the 
# dimension of the crystal that we need to create. 
# Then the content of the unit cell from 'silicon.cell' is
# read and expanded into a crystal of dimen*dimen*dimen 
# unit cells. 
############################################################
#
system mkdir -p DATA
system mkdir -p PLOT
#
variable real,diameter
variable integer,dimen
#
diameter = $1
read
  cell silicon.cell
dimen = int(diameter/lat[1]) + 2
#
read
  cell silicon.cell,dimen,dimen,dimen
############################################################
#
# DISCUS provides a tool that can remove all atoms outside
# a sphere with given radius. All excess atoms are removed
# by the purge command.
#
boundary sphere, diameter/2.
purge
############################################################
#
# The powder pattern is calculated for CuKa, Bragg-Brentano
# geometry.
#
@ex_01.powder   silicon,diameter,$2
############################################################
#
# Macro pdf.mac calculates the Pair distribution function
#
@ex_01.pdf      silicon,diameter,$2
#
###########################################################
#
# Finally we plot the particle 
#
@ex_01.plot.cif silicon,diameter
#
############################################################
# That's it. Use the macro 'kex_01.mac' to display the
# results of the simulation.
############################################################
