kuplot
############################################################
# Plot simulation results of Exercise  8.1 :
############################################################
#
if($0.ne.2) then
  echo "usage: @kex_01 <diameter>, { xray | neutron }"
  continue suite
endif
############################################################
#
# After the macro has finished, use one of the following
# commands to continue (there is no need to *understand*
# the plot macro unless you want to alter it ...) :
# 
############################################################
#
rese
load xy, "DATA/silicon.%6.1F.$2.tth",$1
skal
mark
aver 
achx 2\gH
achy Intensity
mark 10
fnam off
fset 3
grid off
font just,cent
tit1 Silicon nanoparticle
tit2 "Diameter : %6.1f \A ; Powder pattern; Radiation: $2",$1
plot
wait return
#
rese
load xy, "DATA/silicon.%6.1F.$2.gr",$1
skal
mark
aver 
achx r [\A]
achy G(r)
mark 
fnam off
fset 3
grid off
font just,cent
tit1 Silicon nanoparticle
tit2 "Diameter : %6.1f \A ; PDF; Radiation: $2",$1
plot
#
exit    # back to suite level
