kuplot
############################################################
# Plot simulation results of Exercise  3:
############################################################
#
# Run: @kex_03 ni or @kex_03 lmo
#
############################################################
#
reset
load xy,$1_xray.pdf
load xy,$1_neutron.pdf
#
achx r(\A)
achy G(r)
tit1
tit2 PDF
#
fnam off
sleg 1,$1 - X-rays
sleg 2,$1 - Neutrons
#
plot
#
wait return
#
############################################################
exit
